home:
    path: /
    defaults: { _controller: TimetrackerBundle:Employee:index }

timetracker_employees:
    resource: "@TimetrackerBundle/Resources/config/routing.yml"
    prefix:   /employee

api:
    resource: "@TimetrackerBundle/Resources/config/routing_api.yml"

app:
    resource: @AppBundle/Controller/
    type:     annotation

employee:
    resource: @TimetrackerBundle/Controller/
    type:     annotation
